// <auto-generated />
namespace _65Hours.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class userskill_skill_fk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userskill_skill_fk));
        
        string IMigrationMetadata.Id
        {
            get { return "201604060732012_userskill_skill_fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
