// <auto-generated />
namespace _65Hours.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class user_description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_description));
        
        string IMigrationMetadata.Id
        {
            get { return "201604051003054_user_description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
